export enum ErrMessage {
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    NOT_FOUND = 'NOT_FOUND',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    API_KEY_INVALID = 'API_KEY_INVALID',
    CLIENT_INACTIVE = 'CLIENT_INACTIVE',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    RATE_LIMIT = 'RATE_LIMIT',
}
